### ISSUE TITLE
Relic/LC location set as "Trailblazer" regardless of TB's class

### ISSUE THREAD

**Issue by hsven** [IceDynamix/reliquary-archiver#12]
Hello,
Noticed that the output file always sets relics/light cones of the TB as "Trailblazer", regardless of the TB's class.
If I'm not mistaken, this is hard-coded in [this](https://github.com/IceDynamix/reliquary-archiver/blob/5ad0d6e4d14834878b29b13c2c76ef55dfb0153b/src/export/fribbels.rs#L316) line, in the `lookup_avatar_name` function? Do correct me if I'm wrong in my assessment.

Kinda wanted to try to fix this myself, but always getting an `attempt to multiply with overflow` with my unmodified local build, and with my complete inexperience in Rust, I decided to post an issue here.

Sorry for bothering and thank you for your work here!

**Comment by IceDynamix** [comment]
thank you for reporting! i've confirmed with kelz that this is a discrepency to the hsr-scanner output, which outputs it as "TrailblazerPreservation" and "TrailblazerDestruction" respectively. this _was_ a low priority issue, however version 2.2 will make it possible to have relics equipped to all trailblazer paths at the same time, so this will definitely be fixed with next update.
