### ISSUE TITLE
v0.1.7 can't start properly (win nocap installed), even run as admin

### ISSUE THREAD

**Issue by mi1escr0we** [IceDynamix/reliquary-archiver#37]
Win10 22h2, with nocap compatible api installed, run game and double click 0.1.7, nothing happens... no cmd show up, plz help

**Comment by FaeronGaming** [comment]
Open up Command Prompt, Powershell or whatever flavor terminal you prefer. You can run the exe from this window by typing `path\to\reliquary_archiver_x64_v0.1.7.exe`. Since my shell open directly on my home folder this path is `Downloads\reliquary-archiver_x64_v0.1.7.exe` for me.

![image](https://github.com/IceDynamix/reliquary-archiver/assets/3262183/d2a21976-78f9-4d6f-858c-2dfda2356547)

You'll be able to see the error causing the app to crash without the window disappearing

**Comment by partialint** [comment]
> Open up Command Prompt, Powershell or whatever flavor terminal you prefer. You can run the exe from this window by typing `path\to\reliquary_archiver_x64_v0.1.7.exe`. Since my shell open directly on my home folder this path is `Downloads\reliquary-archiver_x64_v0.1.7.exe` for me.
> 
> ![image](https://private-user-images.githubusercontent.com/3262183/345214789-d2a21976-78f9-4d6f-858c-2dfda2356547.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDEyNDIsIm5iZiI6MTcyMjM0MDk0MiwicGF0aCI6Ii8zMjYyMTgzLzM0NTIxNDc4OS1kMmEyMTk3Ni03OGY5LTRkNmYtODU4Yy0yZGZkYTIzNTY1NDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzBUMTIwMjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDJmNTRlZTA3NWZmZTZlMWYyN2UyMzUyNDQ4MzM5MDQ5OGQ1ZjBhZjgwMzIyMWY1ZTc3NDcwOTdhYzBkODNlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.g5qhHsf492LdWHM4rJEjsxLTWW6rSm12wm-iPwAiGfc)
> 
> You'll be able to see the error causing the app to crash without the window disappearing

Similar things happened to me and the error was shown below. I've used it successfully once, but today, it crashed. 
![image](https://github.com/user-attachments/assets/2056d38a-e278-455d-8088-9d279dba6168)
